### PR TITLE
Update syllabus.md

### PR DESCRIPTION
**Pull request by lrshpak**
Added my name and my paper to 6b

### CODE REVIEW

**Comment by gparmer** [comment]
Unfortunately, I just accepted a PR that I believe changed the paper name. Mind updating?

**Comment by lrshpak** [comment]
I just checked and the name for 6b is correct

**Comment by gparmer** [comment]
https://github.com/gwu-iot/collaboration/blob/master/papers/iom11medical_security.pdf

Go to that address. Does it resolve for you?

**Comment by lrshpak** [comment]
okay I think i fixed it

**Comment by gparmer** [comment]
Thanks for all of this!

**Pull request merged**
