### PR TITLE
Added name and pdf link to the syllabus and papers directory (5b discussion leader)

### PR DESCRIPTION
**Pull request by rachellkm**

### CODE REVIEW

**Comment by gparmer** [comment]
This is a huge PR that includes some great things including the renaming of papers (that must have taken so long!!!). However, there are a few things that I'd like to see changed: I believe that renaming some of the papers will break links on the syllabus. The links need to be updated. I also really don't like spaces in file names.  The "2a - blah.pdf" naming scheme should be "2a-blah.pdf". I know it is a huge pain, but would it be possible to make this change? A strategic sed/awk script might automate the change.

**Comment by rachellkm** [comment]
Oops, I actually did not mean to include the renamed papers in this PR! I had initially included this naming scheme into my local repo to better help my eyes. I can definitely revert this to the original version, unless you'd like to keep the "1a", "2a" names without the spaces and have the current links on the syllabus updated. Either change would not be a problem for me to make. Would you prefer the first or latter option? @gparmer

**Comment by gparmer** [comment]
I really like your change. Adding the "2a-x.pdf" is great. If you have the time and are willing to remove the spaces, that would be amazing. That said, if you don't have the time, that's fine. In that case, you can just PR the addition of the links.

In short, I'd prefer the latter, but would understand if you don't have time to do the rename.

**Comment by rachellkm** [comment]
Hi Gabe, I've updated the PR to include the new naming scheme with no white spaces, and also updated the existing links to the papers in the syllabus and papers directory. The links in the syllabus currently break on my forked repo because the newer naming scheme does not yet exist in the collaboration repo (i.e. references github.com/gwu-iot/... rather than github.com/rachellkm/...), but it should work once everything gets merged in. @gparmer

**Comment by gparmer** [comment]
Brilliant, Thanks!

**Pull request merged**
