### PR TITLE
Change 14b and suggest new paper for 16a

### PR DESCRIPTION
**Pull request by ratnadeepb**
Suggesting changing 14b to "Real-Time Scheduling via Reinforcement Learning". This paper makes a strong case about the use of reinforcement learning on real time scheduling. It is a very interesting paper. @AkinoriKahata , @bushidocodes and Ryan Fisk (I have no idea what your GitHub user code is) should look at this change.

Suggesting adding the paper "Hash-routing for Information Centric Networking" for 16a. Information Centric Networking (ICN) has in the past decade emerged as a strong contender for ultimately redesigning the TCP/IP based network. These ideas are based on two things:

1. user-to-content networking (vs node-to-node networking; this is a very deep paradigm change than is apparent here).
2. placing caches of data in the intermediate network.

ICN has recently been making a case for efficient caching in IoT networks and this paper presents a hashing based caching theme that authors claim is robust in the face of various trade-offs.

### CODE REVIEW

**Comment by gparmer** [comment]
1. You added .DS_STORE. Don't do that ;-)
1. Follow the naming scheme of the papers.
1. I think that the ICN paper is fine. I'll bring it up in class, and you can "sell it" to others.
1. I'm very worried about the "deep theory" of the reinforcement learning paper. We'll need to address that in class.

**Comment by ratnadeepb** [comment]
1. Sorry about that. I generally update my gitignore. Forgot that. I will do it.
2. I will change the names of the paper accordingly.

**Comment by ratnadeepb** [comment]
1. Removed .DS_STORE
2. Changed the naming of the papers

**Comment by bushidocodes** [comment]
I glanced through the papers. I share @gparmer's concern about the reinforcement learning paper. How can this be presented in a manner that provides values to our sophomores and perhaps is "progressively enhanced" for those of us higher up the knowledge ziggurat? TOCK was tough. This is much tougher. I wouldn't be comfortable signing up to present that! 

Are you willing to teach this and also commit to having two full packs of [Peeps](https://en.wikipedia.org/wiki/Peeps) and having to eat one every time a sophmore raises hits a button because you went over their heads? (I'll bring the barf bag). 



I personally thing keeping the low power bluetooth paper would better align with the syllabus and be more broadly beneficial.

The ICN paper is more interesting and relevant I think, but if you present this paper specifically, then I think you should augment with some specific information about what this might look like with IOT devices, which off the top of my head seem to map more closely to traditional TCP/IP. What is an addressable thing in the namespace WRT IOT? I single datum? A grouping of data composed from multiple sensors? How are groupings defined? How does that work with relative liveliness for real-time things? So in theory, that's a bit more work: reviewing the paper and then bridging it to the course material.

**Comment by ratnadeepb** [comment]
@bushidocodes I agree, independently reviewing the paper might be difficult. Some background about Markov Decision Processes and so on are required. I found the first 7 videos of this [series](https://www.youtube.com/playlist?list=PLZbbT5o_s2xoWNVdDudn51XM8lOuZ_Njv) very helpful to clarify some basics. Yet, the paper would remain somewhat dense. However, the paper makes a case about the possibility of a different approach at scheduling, which I think is pretty cool. Overall, I believe that it is possible to present this one in a manner that abstracts away the math.

About the ICN paper, yes ICN implementations like Named Data Networking (NDN) is quite the pipe dream and most systems, including IoT systems, still remain in the TCP-land. But the important takeaway from the idea is the fact that end-users are trying to get to data and not a specific node on the Internet (it really took me a while for that to sink in). And one way of doing that is caching data progressively nearer to the edge. A great analogy for this are CDNs (Content Delivery Network) that are instrumental in allowing us to watch NetFlix while we ride the metro.

**Comment by gparmer** [comment]
My proposal: Lets add the ICN paper into one of the free slots for the time being. I'm not sure I want to inflict the other paper on folks at this point.

I'm also happy to do a "lightening round" where people can spend 10 minutes talking about a paper that others do *not* read. This could be both fun, and a way for people to understand the directions they can go after the class. For that, you could certainly read the RL paper and present it.

What do you all think?

**Comment by ratnadeepb** [comment]
Makes sense to me. If Sean found the paper difficult, then others definitely would too. And now I am not keen on inflicting that kind of pain on the class! :)

**Comment by ratnadeepb** [comment]
I have reverted 14b and added the ICN paper only for 16a.

**Comment by bushidocodes** [comment]
This all sounds good to me now. 👍. A lightening round also sounds like a reasonable idea if there is time for it.

**Comment by gparmer** [comment]
This PR is pretty strange. Look at the files.

1. There is .DS_STORE still...
2. The formatting is completely different, and **s are changed to __s. I'm fine with the idea of your change, but not with all of these changes.

**Comment by ratnadeepb** [comment]
2 was an issue with the markdown linter I was using. Sorry about that.
The .DS_Store confuses me. I don't see it in my git pathspec anymore

**Comment by gparmer** [comment]
Still a huge # of changes due to the linter (https://github.com/gwu-iot/collaboration/pull/59/files). Should we close the PR, and you can reopen it?

**Comment by ratnadeepb** [comment]
Makes sense. I'll need a couple of days to undo all this too.

**Pull request closed without merging**
